module.exports = {
    Temperature:   {type: 'number',  role: 'value.temperature',        read: true, write: false, unit: '°C'},
    Humidity:      {type: 'number',  role: 'value.humidity',           read: true, write: false, unit: '%'},
    Temperatur:    {type: 'number',  role: 'value.temperature',        read: true, write: false, unit: '°C'},
    Feuchtigkeit:  {type: 'number',  role: 'value.humidity',           read: true, write: false, unit: '%'},
    Vcc:           {type: 'number',  role: 'value.voltage',            read: true, write: false, unit: 'V'},
    VCC:           {type: 'number',  role: 'value.voltage',            read: true, write: false, unit: 'V'},
    Laufzeit:      {type: 'number',  role: 'value.duration',           read: true, write: false, unit: 'hours'}, /// ?
    RSSI:          {type: 'number',  role: 'value.rssi',               read: true, write: false},
    POWER:         {type: 'boolean', role: 'switch',                   read: true, write: true,  storeMap: true},
    POWER1:        {type: 'boolean', role: 'switch',                   read: true, write: true,  storeMap: true},
    POWER2:        {type: 'boolean', role: 'switch',                   read: true, write: true,  storeMap: true},
    POWER3:        {type: 'boolean', role: 'switch',                   read: true, write: true,  storeMap: true},
    POWER4:        {type: 'boolean', role: 'switch',                   read: true, write: true,  storeMap: true},
    POWER5:        {type: 'boolean', role: 'switch',                   read: true, write: true,  storeMap: true},
    POWER6:        {type: 'boolean', role: 'switch',                   read: true, write: true,  storeMap: true},
    POWER7:        {type: 'boolean', role: 'switch',                   read: true, write: true,  storeMap: true},
    POWER8:        {type: 'boolean', role: 'switch',                   read: true, write: true,  storeMap: true},
    Switch1:       {type: 'boolean', role: 'switch',                   read: true, write: false},
    Switch2:       {type: 'boolean', role: 'switch',                   read: true, write: false},
    Switch3:       {type: 'boolean', role: 'switch',                   read: true, write: false},
    Switch4:       {type: 'boolean', role: 'switch',                   read: true, write: false},
    Total:         {type: 'number',  role: 'value.power.consumption',  read: true, write: false, unit: 'kWh'},
    Today:         {type: 'number',  role: 'value.power.consumption',  read: true, write: false, unit: 'kWh'},
    heute:         {type: 'number',  role: 'value.power.consumption',  read: true, write: false, unit: 'kWh'},
    Yesterday:     {type: 'number',  role: 'value.power.consumption',  read: true, write: false, unit: 'kWh'},
    gestern:       {type: 'number',  role: 'value.power.consumption',  read: true, write: false, unit: 'kWh'},
    Faktor:        {type: 'number',  role: 'value',                    read: true, write: false},
    Factor:        {type: 'number',  role: 'value',                    read: true, write: false},
    Power:         {type: 'number',  role: 'value.power.consumption',  read: true, write: false, unit: 'W'},
    Leistung:      {type: 'number',  role: 'value.power.consumption',  read: true, write: false, unit: 'W'},
    Voltage:       {type: 'number',  role: 'value.voltage',            read: true, write: false, unit: 'V'},
    Spannung:      {type: 'number',  role: 'value.voltage',            read: true, write: false, unit: 'V'},
    Current:       {type: 'number',  role: 'value.current',            read: true, write: false, unit: 'A'},
    Strom:         {type: 'number',  role: 'value.current',            read: true, write: false, unit: 'A'},
    Punkt:         {type: 'number',  role: 'value',                    read: true, write: false, unit: '?'}, /// ?
    Counter1:      {type: 'number',  role: 'value',                    read: true, write: false},
    Counter2:      {type: 'number',  role: 'value',                    read: true, write: false},
    Counter3:      {type: 'number',  role: 'value',                    read: true, write: false},
    Counter4:      {type: 'number',  role: 'value',                    read: true, write: false},
    Pressure:      {type: 'number',  role: 'value.pressure',           read: true, write: false, unit: 'P'},
    SeaPressure:   {type: 'number',  role: 'value.pressure',           read: true, write: false, unit: 'P'},
    Druck:         {type: 'number',  role: 'value.pressure',           read: true, write: false, unit: 'P'},
    'Approx. Altitude': {type: 'number',  role: 'value.altitude',      read: true, write: false, unit: 'm'},
    Module:        {type: 'string',  role: 'state',                    read: true, write: false},
    Version:       {type: 'string',  role: 'state',                    read: true, write: false},
    Hostname:      {type: 'string',  role: 'state',                    read: true, write: false},
    IPAddress:     {type: 'string',  role: 'state',                    read: true, write: false},
    IPaddress:     {type: 'string',  role: 'state',                    read: true, write: false},
    RestartReason: {type: 'string',  role: 'state',                    read: true, write: false},
	Uptime:        {type: 'string',  role: 'state',                    read: true, write: false},
    CarbonDioxide: {type: 'number',  role: 'value.CO2',                read: true, write: false, unit: 'ppm'},
    Illuminance:   {type: 'number',  role: 'value.illuminance',        read: true, write: false, unit: 'lx'},
    Analog0:       {type: 'number',  role: 'value',                    read: true, write: false},
    Analog1:       {type: 'number',  role: 'value',                    read: true, write: false},
    Analog2:       {type: 'number',  role: 'value',                    read: true, write: false},
    Analog3:       {type: 'number',  role: 'value',                    read: true, write: false},
    Light:         {type: 'number',  role: 'value',                    read: true, write: false, unit: 'lx'},
    Noise:         {type: 'number',  role: 'value',                    read: true, write: false, unit: 'dB'},
    AirQuality:    {type: 'number',  role: 'value',                    read: true, write: false, unit: '%'},
    Total_in:      {type: 'number',  role: 'value.power.consumption',  read: true, write: false, unit: 'kWh'},
    Total_out:     {type: 'number',  role: 'value.power.consumption',  read: true, write: false, unit: 'kWh'},
    Power_curr:    {type: 'number',  role: 'value.power.consumption',  read: true, write: false, unit: 'W'},
    Outsidetemp:   {type: 'number',  role: 'value.temperature',        read: true, write: false, unit: '°C'},
    Roomtemp:      {type: 'number',  role: 'value.temperature',        read: true, write: false, unit: '°C'},
    Boiler:        {type: 'number',  role: 'value.temperature',        read: true, write: false, unit: '°C'},
    Returns:       {type: 'number',  role: 'value.temperature',        read: true, write: false, unit: '°C'},
    Warmwater:     {type: 'number',  role: 'value.temperature',        read: true, write: false, unit: '°C'},
    Burner:        {type: 'number',  role: 'value',                    read: true, write: false},
    Status:        {type: 'number',  role: 'value',                    read: true, write: false},
    Solarstorage:  {type: 'number',  role: 'value.temperature',        read: true, write: false, unit: '°C'},
    Collector:     {type: 'number',  role: 'value.temperature',        read: true, write: false, unit: '°C'},
    Solarpump:     {type: 'number',  role: 'value',                    read: true, write: false},
    TVOC:          {type: 'number',  role: 'value.tvoc',		       read: true, write: false, unit: 'ppb'},
    eCO2:          {type: 'number',  role: 'value.eco2',               read: true, write: false, unit: 'ppm'},
    Dimmer:        {type: 'number',  role: 'level.dimmer',             read: true, write: true},
    Color:         {type: 'string',  role: 'level.color.rgb',          read: true, write: true},
    Hue:           {type: 'number',  role: 'level.color.hue',          read: true, write: true},
    Saturation:    {type: 'number',  role: 'level.color.saturation',   read: true, write: true},
    Red:           {type: 'number',  role: 'level.color.red',          read: true, write: true},
    Green:         {type: 'number',  role: 'level.color.green',        read: true, write: true},
    Blue:          {type: 'number',  role: 'level.color.blue',         read: true, write: true},
    WW:            {type: 'number',  role: 'level.color.ww',           read: true, write: true},
    WW_POWER:      {type: 'boolean', role: 'switch',                   read: true, write: true,  storeMap: true},
    RGB_POWER:     {type: 'boolean', role: 'switch',                   read: true, write: true,  storeMap: true},
    CW:            {type: 'number',  role: 'level.color.cw',           read: true, write: true},
    CT:            {type: 'number',  role: 'level.color.temp',         read: true, write: true},
    CW_POWER:      {type: 'boolean', role: 'switch',                   read: true, write: true,  storeMap: true},
    Scheme:        {type: 'number',  role: 'value',                    read: true, write: false},
    UvLevel:       {type: 'number',  role: 'value',                    read: true, write: false},
    Latitude:      {type: 'number',  role: 'value.gps.latitude',       read: true, write: true, unit: '°'},
    Longitude:     {type: 'number',  role: 'value.gps.longitude',      read: true, write: true, unit: '°'},
    Speed:         {type: 'number',  role: 'value',                    read: true, write: false},
    Wakeup:        {type: 'string',  role: 'state',                    read: true, write: true},
    IrReceived:    {type: 'object',  role: 'state',                    read: true, write: true},
    Protocol:      {type: 'string',  role: 'state',                    read: true, write: true},
    Bits:          {type: 'number',  role: 'value',                    read: true, write: false},
	LED_Mode:      {type: 'string',  role: 'state',                    read: true, write: true},
    Data:          {type: 'string',  role: 'state',                    read: true, write: true},
	Fade:          {type: 'boolean',  role: 'switch',                  read: true, write: true},
    'PM2.5':       {type: 'number',  role: 'value',                    read: true, write: false, unit: 'ug/m3'},
    PM10:          {type: 'number',  role: 'value',                    read: true, write: false, unit: 'ug/m3'},
	Channel:       {type: 'array',   role: 'level',                    read: true, write: true},
	HSBColor:      {type: 'string',  role: 'value.hsb',                read: true, write: true}
};


